# .github/workflows/powerline-ci.yml
name: Power Line CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 1'  # Каждый понедельник в 2:00 (ночной прогон)

jobs:
  test:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install system dependencies for OpenCV
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
        
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov opencv-python-headless
        
    - name: Run critical physics tests
      run: |
        pytest tests/test_tension_calculation.py tests/test_safety_criteria.py -v
        
    - name: Run all tests with coverage
      run: |
        pytest tests/ -v --cov=src/ --cov-report=html --cov-report=xml
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report-${{ matrix.python-version }}
        path: htmlcov/
        
    - name: Run demo with synthetic data
      run: |
        python examples/demo_pipeline.py --test-mode --synthetic-data
